sudo: false
language: java

jobs:
  include:
    - script: mvn test
      jdk: oraclejdk8
    - stage: Coveralls code coverage
      jdk: oraclejdk8
      script: mvn clean cobertura:cobertura coveralls:report
    - stage: GitHub Release
      jdk: oraclejdk8
      script: mvn package
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file_glob: true
        file: gui/target/similarImage*.jar
        file: cli/target/similarImage*.jar
        on:
          tags: true